# Generated by Django 4.0.5 on 2022-06-17 15:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=200, verbose_name='Password')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service', to='Services.service')),
            ],
        ),
    ]
